### ISSUE TITLE
Buttercup Android not starting on Huawei P9 Lite

### ISSUE THREAD

**Issue by jnten** [buttercup/buttercup-mobile#164] opened 2019-06-20 21:09 UTC
Hi,

I am using Buttercup on Linux already with a vault on Google Drive. I was trying to set it up on my Android phone as well.

Downloaded the latest version from Google Play Store. Prompt came up to give permissions to overwrite which I granted.

After that launching the app just brings up a white screen briefly. After that it closes.

Android - not sure about the version. Phone information says
Kernel 4.1.18-g4ae3101

Android security patch level March 1, 2017

Huawei P9 Lite

**Comment by corderop** [comment] 2019-06-29 22:22
In my Xiaomi redmi 4X, with android 7.1.2, the same thing happens. I have the latest version from Google Play, 1.8.2 exactly.

**Comment by perry-mitchell** [comment] 2019-07-01 19:19
@corderop Your android version is too old I'm afraid. Google also recommends not using less than 8, and we're forced to follow their guidance here.

**Comment by perry-mitchell** [comment] 2019-07-01 19:21
@jnten I believe that kernel version is also Android 7, which means it's probably out of date as well.

Please try updating your device to ensure you're running android 8 or newer - it should not crash then. If you find that you are indeed using android 8 or newer and it's still crashing, we can continue debugging. I'm sorry that I can't be of more help.

I'll close this for now but we can reopen if the issue is something else.

**Closed by perry-mitchell** 2019-07-01 19:21 UTC

**Comment by timojuonoja** [comment] 2019-08-20 05:22
Why oh why the support for older than Android 8 is dropped? What is the reason? I was going to replace Lastpass to Buttercup but this is a real deal-breaker.. this forces me to drop Buttercup as an option and really pushes me to find another alternative. So can you please share the reason behind dropping Android 6 support? Google's recommendation is not a real reason...

Manufacturers are not upgrading the Android versions constantly: for high-end models they are but for low-end models not. If phone's first Android is for example version 6, it will stick into that and you can't do anything to it. For example, I bought to my boy Huawei Y6 2017 last year at autumn with Android 6 and it is never going to get Android 8..

**Comment by timojuonoja** [comment] 2019-09-14 09:11
@perry-mitchell Any reason for dropping Android 6 support? You are just referring to Google's recommendation which is for NEW applications, but older ones can still continue to support for example Android 6 if they have previously done so.
