### ISSUE TITLE
TOTP Codes Disappear from Menu

### ISSUE THREAD

**Issue by sambhavsaggi** [buttercup/buttercup-mobile#230] opened 2020-02-24 03:06 UTC
When opening the two-factor codes section in the app, none (or only a few codes) appear. To reproduce, go to a website that supports two-factor auth, add their code via QR, add to vault, and wait. Occasionally the codes do not appear in the menu but are saved in the vault.

iOS 1.13 (Jailbroken, issue persists on non-jailbroken device)

iPhone 6s

**Comment by perry-mitchell** [comment] 2020-03-01 09:27
When adding them via the camera, you need to make sure to add them to an **entry**. Are you doing this? :)

**Comment by sambhavsaggi** [comment] 2020-03-01 11:43
The TOTP codes are in the entry, but no TOTP passcodes are generated. Nothing shows up in the “codes” tab below.
![A56851BA-F507-4137-A7CC-A861269C9697](https://user-images.githubusercontent.com/17993169/75625002-d3c77c00-5b87-11ea-83ce-4f3b4286b1d3.jpeg)

**Comment by perry-mitchell** [comment] 2020-03-02 20:01
@sambhavsaggi Strange.. Can you verify that the code is OK and valid?

Can you try generating a TOTP URI [here](https://stefansundin.github.io/2fa-qr/)? Just to see if that works? Make sure to set the property as type OTP.

**Comment by sambhavsaggi** [comment] 2020-03-04 14:18
I added to TOTP URI, and it appeared in the "Codes" section. However, the code entry disappeared from the "Codes" section but remained in the entry.

**Comment by perry-mitchell** [comment] 2020-03-13 17:52
> However, the code entry disappeared from the "Codes" section 

I don't know what you mean by "code entry". The codes section only shows TOTP codes - these items are not entries - one entry might have multiple TOTP codes.

**Comment by sambhavsaggi** [comment] 2020-03-18 02:12
Sorry for the delay

![image](https://user-images.githubusercontent.com/17993169/76918264-4df04400-689c-11ea-9854-eb2dec795c20.jpeg)

This is the codes menu I was talking about

**Comment by sambhavsaggi** [comment] 2020-03-22 00:21
I believe that this is a save issue with Nextcloud, as it is not reproducible with GDrive, but is with NC.

**Comment by perry-mitchell** [comment] 2020-06-30 21:53
I'm going to close this for now as it's not reproducible. It may be an inherent issue with Nextcloud, which is famous for not supporting WebDAV correctly (it may not be saving changes properly for all clients, due to CORS issues).

**Closed by perry-mitchell** 2020-06-30 21:53 UTC
