### ISSUE TITLE
Connecting to google drive fails

### ISSUE THREAD

**Issue by jsbberlin** [buttercup/buttercup-mobile#203] opened 2019-11-26 12:41 UTC
I try to connect to google drive on android. Clicking on 'authenticate' prompts me to select an account, clicking that account starts a process, that does not end (spinner will not finish)

OS is Android 9 / iOS 12.3.1_

Device Nokia  7.2

Can I provide you any more information?

**Comment by perry-mitchell** [comment] 2019-11-29 14:50
I've not been able to reproduce this, unfortunately. If it gets that far it's most likely not the Google Play services issue that others have seen. We don't obviously own a heap of Android phones so it's close to impossible to see if it's a device issue.

If you have any development interest/experience we'd invite you to look at the codebase to test it for yourself - otherwise I'm afraid there's not much we can do or recommend until someone can dive deeper on your particular device/configuration.

**Comment by alxwrd** [comment] 2019-12-02 16:30
I'm experiencing the same issue. Android 10, Google Pixel 4.

Possibly related react-native-community/react-native-google-signin#663? Although that issue seems to be related to `GoogleSignin.getTokens()`, and Buttercup mobile uses [buttercup/google-oauth2-client](https://github.com/buttercup/google-oauth2-client) to fetch the token?

I'll see if I can get an environment set up to have a look at this.

**Comment by arajdon** [comment] 2019-12-12 07:09
> I've not been able to reproduce this, unfortunately. If it gets that far it's most likely not the Google Play services issue that others have seen.

Each time (after some minutes) I want to add a new or existing vault from Google Drive, I'm getting a mail notification from Google saying that Buttercup has accessed my documents.

First of all, I don't think this is a wanted behavior. I'm using Keepass2Android with Drive as storage and i just had to once authorize the app for it. Never got a notification mail from adding other vaults.

Could it be that after a timeout, when trying to access the vault, any authentication token has expired, denying the access to Drive? Or it is a wrong implementation of the API..


As you can see I've already got a vault.
![Screenshot_20191212-080206](https://user-images.githubusercontent.com/7300870/70689987-eed7cd80-1cb5-11ea-89d4-40d9d79a20bc.png)

When trying to add a new one, I need to confirm access from buttercup, even though it already has got permission.
![Screenshot_20191212-080241~2](https://user-images.githubusercontent.com/7300870/70689959-e089b180-1cb5-11ea-9ce6-e962de9b5e8a.png)

But this step is required to be able to "connect" to drive before adding new vaults.

**Comment by perry-mitchell** [comment] 2019-12-17 08:28
Google expires our token every hour.. and I haven’t seen an option to change that. I think we need to experiment with the tighter permissions and see if that has an impact.

**Comment by arajdon** [comment] 2019-12-20 20:01
Found out Keepass2Android is on Github too: https://github.com/PhilippC/keepass2android

**Comment by AdamTheRedBaron** [comment] 2019-12-30 17:46
I am unable to connect the mobile app to my Google Drive. The app authenticates fine, but when I hit "connect" I just get the Connecting overlay and spinner which then does nothing else. I'm using the latest version of the App from Google Play, Android 10 on OnePlus 6T, connecting to Google Drive on a G Suite account. The archive is in a folder named Buttercup in the GDrive root. I can connect no problem from the desktop apps on W10 and Opensuse Linux.

**Comment by DanielWeeber** [comment] 2019-12-30 22:18
Same here on newest iOS

**Comment by AdamTheRedBaron** [comment] 2019-12-31 15:35
I think it is the same issue that exists on the Browser Extension. If you have a large gDrive, it can take a long time for the app to try and recreate the entire directory and folder structure.

**Comment by DanielWeeber** [comment] 2019-12-31 15:38
I have only a few files (<50) and folders (<5) on my drive. But yeah, Browser extension is also very slow and took minutes to find the file.

**Comment by jsbberlin** [comment] 2020-01-06 15:03
Pretty much the same on my side: just a few files (and only one folder). I doubt that this is the reason. Unfortunately I just figured out how to connect to buttercup file on google drive using the browser extentension (but that is probably a different story ...)

**Comment by perry-mitchell** [comment] 2022-08-29 19:51
Closing this as I can't reproduce it. If a reproducible case can be documented and reliably followed to present the bug I'll gladly reopen.

**Closed by perry-mitchell** 2022-08-29 19:51 UTC
Labels: Priority: High, Status: Available, Type: Bug, Platform: Android
