### ISSUE TITLE
Cannot add new WebDAV URL to buttercup Android App

### ISSUE THREAD

**Issue by gschoenberger** [buttercup/buttercup-mobile#353] opened 2024-02-18 08:35 UTC
Hey Buttercup team!
Thanks for the great password manager, I am a Buttercup long time user.

Recently adding a new Buttercup WebDAV vault stopped working for me. This is the request on the server side when I try to connect:
```
91.114.XX.XX XXX.XXX.at - zeus [18/Feb/2024:09:28:54 +0100] "PROPFIND /remote.php/dav/files/zeus/ HTTP/2.0" 207 331 "-" "okhttp/4.9.2" "-" "AT" "TLSv1.3/TLS_AES_256_GCM_SHA384" "63" "0.023"
```
Return code 207 should be quite OK.

Any hints on how to solve the connection issue?
The owncloud instance is served by an Apache2 server behind a NGINX proxy.

If any further details are needed just let me know!

**Comment by fh-vocalls** [comment] 2024-03-13 14:22
Hello,

I have got new Android around 8.2.2024 and I still have problem with adding new WebDAV vault (Connection failed - WebDAV connection test failed). On older phone, where vault was added sooner, vault is working properly.

I'm using nextcloud behind nginx proxy (valid tls cert) and on server side I also can see HTTP 207 code, just as @gschoenberger . 

It seems it can be same/similar issue as https://github.com/buttercup/buttercup-mobile/issues/352
Desktop app (linux) works without any issue.

If there are other useful information, that would help to figure this out, let me know.

**Comment by gschoenberger** [comment] 2024-03-14 05:16
@perry-mitchell Could you give us some hints if we need specific WebDAV settings on NGINX.
Currently my work-around is to use Google Drive to sync my Buttercup passwords, but I want definitively go back to WebDAV with owncloud.

Tested on 2 different Android 13 phones (Motorola), WebDAV is not working with the 207 status code on the NGINX side.

THX a lot!

**Comment by ScribblerCoder** [comment] 2024-03-16 19:14
same here :/

**Comment by ModernOctave** [comment] 2024-03-19 15:55
Hi, even I'm have the same issue...

**Comment by perry-mitchell** [comment] 2024-03-19 17:53
This is a known issue and is on our short list to fix. Something has broken on the iOS side, by Apple, as we haven't made any changes here. I'll try to get to it asap.

Please refrain from me-too posts as it's evident this is now widespread. 

Thanks

**Comment by julianpoemp** [comment] 2024-05-02 10:47
was fixed in v2.6.2. This issue can be closed.

**Comment by sousa43** [comment] 2024-05-02 15:58
> was fixed in v2.6.2. This issue can be closed.

Hi, the problem still exists, even on new equipment

**Comment by perry-mitchell** [comment] 2024-05-06 18:38
@sousa43 I can't reproduce this, so I'll close for now. If some manner of reproduction is possible I'll gladly reopen.

**Closed by perry-mitchell** 2024-05-06 18:38 UTC

**Comment by sousa43** [comment] 2024-05-07 11:18
@perry-mitchell What you need to show to you the problem?
Fotos/Videos from every phone i tested?
Phones specs?
Web dav settings?

**Comment by perry-mitchell** [comment] 2024-05-07 12:08
@sousa43 Screenshot of the error, phone specs, and WebDAV settings (if relevant).. obviously without identifying parameters. That'd be a start.

**Comment by sousa43** [comment] 2024-05-07 12:34
The phone 2 Already has a working vault but if i try adding a new gives the same error of a phone 1.
Phone 1 dont have vault.

Webdav Server - Synology NAS with latest version.

![phone2 1](https://github.com/buttercup/buttercup-mobile/assets/13574555/007b0be6-1b5f-48d6-ad05-8df8269d192e)
![phone1](https://github.com/buttercup/buttercup-mobile/assets/13574555/b1c4a1ef-ad0a-40f9-bf6a-3c89759ab4ce)
![phone1 1](https://github.com/buttercup/buttercup-mobile/assets/13574555/3d1528f0-6283-4e88-9409-532e546c4aef)
![phone2](https://github.com/buttercup/buttercup-mobile/assets/13574555/4cb6f26c-affd-457b-b980-75a18063ad9b)

Phone1 - Samsung Galaxy M12 Android 13
Phone 2 - Samsung Galaxy Fold 4 Android 14

I have other phones to test if you need.

**Comment by julianpoemp** [comment] 2024-05-07 12:43
@sousa43  perhaps it's an SSL certificate issue. Is the certificate a self-signed certificate? Are you accessing your NAS via a domain or the IP address? Is the certificate still valid?

**Comment by sousa43** [comment] 2024-05-07 12:48
> @sousa43 perhaps it's a SSL certificate issue. Is the certificate a self-signed certificate? Are you accessing your NAS via a domain or the IP address? Is the certificate still valid?

Hi it has a domain with a valid lets encript certificate

**Comment by perry-mitchell** [comment] 2024-05-08 04:52
Is it a publicly registered address? If not you probably still need to trust the certificate locally on the device. I'm not super familiar with this process on Android. We added support for self-signed certificates a long time ago and that functionality hasn't been altered, I don't think.

Regardless, this problem isn't related to the original issue I'm afraid. And this is an area that I'm not very familiar with, sorry.
