### ISSUE TITLE
Crash when adding nextcloud archive

### ISSUE THREAD

**Issue by SamuelNitsche** [buttercup/buttercup-mobile#140] opened 2019-02-04 12:40 UTC
Every second or third time I tap on "Nextcloud" in the "Add archive" section the app crashes on the iPhone. I have an iPhone X with iOS 12.1.1 and the latest version of the app.

**Comment by perry-mitchell** [comment] 2019-02-07 19:48
Thanks @SamuelNitsche - We'll try to reproduce this soon.

**Comment by SamuelNitsche** [comment] 2019-02-08 08:02
Thank you! Feel free to contact me if you need more information.

**Comment by perry-mitchell** [comment] 2020-01-26 20:06
Can't reproduce. Will close this for now.

We're also about to stop supporting ownCloud and Nextcloud as first-party services on mobile (they already aren't on the other platforms).

**Closed by perry-mitchell** 2020-01-26 20:06 UTC
Labels: Status: Pending
