### ISSUE TITLE
Unable to add or create a vault that is stored in Google Drive.,

### ISSUE THREAD

**Issue by dutchtux3000** [buttercup/buttercup-mobile#253] opened 2020-10-22 07:35 UTC
** Describe the issue you're having **
Trying to add existing vault that is stored in Google Drive.

_What were you doing when the issue occurred? How do we reproduce it?_
Adding a Vault that is stored on a Google Drive Account.

** What OS version are you using **
Android 10 and 11

** What device are you using **
OnePlust 5t with Android 10 
OnePlus 8t with Android 11.

----------------------------------------------------------------------
After downloading the latest master branch and doing the same actions I got the following warnings in the developer console.
I hope this will help.

**When authentication with google is completed.**
`Warning: The provided value 'auto' is not a valid 'responseType'.`

reactConsoleErrorHandler | @ | ExceptionsManager.js:126
-- | -- | --
console.error | @ | YellowBox.js:63
printWarning | @ | warning.js:30
warning | @ | warning.js:51
set | @ | XMLHttpRequest.js:182
__request | @ | request.js:219
tryCallTwo | @ | core.js:45
doResolve | @ | core.js:200
Promise | @ | core.js:66
request | @ | request.js:176
__executeSequence | @ | functions.js:10
execute | @ | index.js:95
getDirectoryContents | @ | directoryContents.js:89
mapDirectoryContents | @ | directoryContents.js:131
mapDirectoryContents | @ | index.js:80
getDirectoryContents | @ | remote.js:59
testRemoteFSConnection | @ | remote.js:36
getGoogleDriveConnection | @ | remote.js:13
createRemoteConnection | @ | explorerConnection.js:99
handleConnectionCreation$ | @ | RemoteConnectPage.js:51

**This also happening when I tap Connect.**
`Warning: The provided value 'auto' is not a valid 'responseType'.`

reactConsoleErrorHandler | @ | ExceptionsManager.js:126
-- | -- | --
console.error | @ | YellowBox.js:63
printWarning | @ | warning.js:30
warning | @ | warning.js:51
set | @ | XMLHttpRequest.js:182
__request | @ | request.js:219
tryCallTwo | @ | core.js:45
doResolve | @ | core.js:200
Promise | @ | core.js:66
request | @ | request.js:176
__executeSequence | @ | functions.js:10
execute | @ | index.js:95
getDirectoryContents | @ | directoryContents.js:89
mapDirectoryContents | @ | directoryContents.js:131
mapDirectoryContents | @ | index.js:80
getDirectoryContents | @ | remote.js:59
testRemoteFSConnection | @ | remote.js:36
getGoogleDriveConnection | @ | remote.js:13
createRemoteConnection | @ | explorerConnection.js:99
handleConnectionCreation$ | @ | RemoteConnectPage.js:51

**Comment by perry-mitchell** [comment] 2020-10-23 06:04
> Warning: The provided value 'auto' is not a valid 'responseType'

These are non-errors, which will be fixed soon. They're basically ignored though, and not the cause of your issue.

What exactly happens when you try adding a vault? Any errors? Crashes?

**Comment by dutchtux3000** [comment] 2020-10-23 07:19
I am not able to select a vault from the file list. 
The list stays empty with nothing happening.

**Comment by dutchtux3000** [comment] 2020-10-23 07:55
After looking around I was able to see the network traffic and see. That I am not getting any results back.
I am getting the following response back:
`
{
"files": []
}
`

**Comment by bluezod** [comment] 2020-11-30 02:11
I have encountered the same issue in iOS 14. File/folder list was empty after authorizing Google Drive

**Comment by perry-mitchell** [comment] 2020-12-06 14:21
Any such bug or issue would be present in our [googledrive-client library](https://github.com/buttercup/googledrive-client), in case someone has the time to investigate further before we do. I haven't yet seen any issue myself and can connect to my Google Drive just fine.

@bluezod Any special circumstances with your Google Drive account? Are the files owned by yourself and not shared/mounted?

**Comment by cyrilnaimi** [comment] 2021-09-27 16:46
Hi,
I got the same bug on IpadOS14 (will try with Ipados15 later)

I have my vaults on google drive (in a folder).
When I authenticate buttercup on iPad to the drive everything "seems" working but when  need to connect my vault the drive files / folder list is empty. 

My vaults are working fine on android and Mac OS of course. 

Can I help to debug this ? how ? thanks a lot for the support

**Comment by perry-mitchell** [comment] 2022-01-23 16:46
Please try the new 2.2.0 app version if you're still using Buttercup - it has a new permissions checkbox for Google permissions. Consider granting full permissions so you can view all files, and let me know if that fixes the problem. Would appreciate the feedback 🙏

**Comment by danitt** [comment] 2022-01-26 14:04
> I am not able to select a vault from the file list. I am just getting a empty list. Even waiting for a couple of minutes.

@dutchtux3000 can confirm the latest update fixes the issue on my android 🚀

**Closed** 2022-01-28 12:47 UTC
