### ISSUE TITLE
Trying Sign-in on Google Auth from Buttercup mobile 

### ISSUE THREAD

**Issue by dizyaa** [buttercup/buttercup-mobile#339] opened 2023-04-29 10:32 UTC
1. Add vault
2. Try Connect Google Drive
3. Choose any google account
4. Catch Error 

![telegram-cloud-photo-size-2-5362086268000915519-y](https://user-images.githubusercontent.com/53047160/235298149-aac21149-489e-4df6-b8ca-7af09f91c6c2.jpg)
<img width="1624" alt="image" src="https://user-images.githubusercontent.com/53047160/235298152-cd700a00-6734-4c1b-a465-2a280042a184.png">

**Comment by perry-mitchell** [comment] 2023-05-02 18:27
Duplicate of #337

**Closed by perry-mitchell** 2023-05-02 18:27 UTC
