### ISSUE TITLE
[IOS/Android] Google reauthentication 

### ISSUE THREAD

**Issue by QuinsZouls** [buttercup/buttercup-mobile#318] opened 2022-07-27 19:55 UTC
When I add a new vault with Google drive, the app redirect to a google grant permission page, I grant access to my Drive account and It works fine, I can access to my vault with password or FaceID/fingerprint fine for a fews days, the problem is when I open the app after one week and then it redirect me again to google  for grant permissions :/, this shouldn't happen because i granted those permissions, so i have to grant those permissions again to have access to my vault, i have this problem on Android (Galaxy Tab s7) and IOS (Iphone 11).
Mobile authentication shuld be similar to a browser extension (It ask only one time por those permissions)

**Comment by perry-mitchell** [comment] 2022-08-29 19:53
Dupe of #304

**Closed by perry-mitchell** 2022-08-29 19:53 UTC
